VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "KPIOnTimeResultPallet"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public str_id As String

Public str_date As String
Public str_time As String

Public str_shift As String
Public str_shift_type As String

Public str_building As String
Public str_process_name As String
Public str_process_step As String

Public str_kpi_id As String
Public str_kpi_name As String
Public str_kpi_status As String
