VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "KPIOnTimeResultClient"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public str_date As String
Public str_time As String
Public str_shift As String

Public str_process_id As String
Public str_process_step As String

Public str_kpi_id As String
Public str_kpi_target As String
Public str_kpi_actual As String

Public str_task As String
Public str_building As String

Public str_datetime_id As String

'Public INT_OFFSET_PROCESS_NAME As Integer
'Public INT_OFFSET_PROCESS_STEP As Integer
'
'Public INT_OFFSET_KPI_ID As Integer
'
'Public INT_OFFSET_KPI_TARGET As Integer
'Public INT_OFFSET_KPI_ACTUAL As Integer
'
'Public INT_OFFSET_TASK As Integer
'Public INT_OFFSET_BUILDING As Integer
'
'Public INT_DATETIME_ID As Integer
